// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.dp.blackhole.common;

public final class MessagePB {
  private MessagePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .blackhole.Message.MessageType type = 1;
    /**
     * <code>required .blackhole.Message.MessageType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .blackhole.Message.MessageType type = 1;</code>
     */
    com.dp.blackhole.common.MessagePB.Message.MessageType getType();

    // optional .blackhole.AppReg appReg = 2;
    /**
     * <code>optional .blackhole.AppReg appReg = 2;</code>
     */
    boolean hasAppReg();
    /**
     * <code>optional .blackhole.AppReg appReg = 2;</code>
     */
    com.dp.blackhole.common.AppRegPB.AppReg getAppReg();
    /**
     * <code>optional .blackhole.AppReg appReg = 2;</code>
     */
    com.dp.blackhole.common.AppRegPB.AppRegOrBuilder getAppRegOrBuilder();

    // optional .blackhole.AssignCollector assignCollector = 3;
    /**
     * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
     */
    boolean hasAssignCollector();
    /**
     * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
     */
    com.dp.blackhole.common.AssignCollectorPB.AssignCollector getAssignCollector();
    /**
     * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
     */
    com.dp.blackhole.common.AssignCollectorPB.AssignCollectorOrBuilder getAssignCollectorOrBuilder();

    // optional .blackhole.AppRoll appRoll = 4;
    /**
     * <code>optional .blackhole.AppRoll appRoll = 4;</code>
     */
    boolean hasAppRoll();
    /**
     * <code>optional .blackhole.AppRoll appRoll = 4;</code>
     */
    com.dp.blackhole.common.AppRollPB.AppRoll getAppRoll();
    /**
     * <code>optional .blackhole.AppRoll appRoll = 4;</code>
     */
    com.dp.blackhole.common.AppRollPB.AppRollOrBuilder getAppRollOrBuilder();
  }
  /**
   * Protobuf type {@code blackhole.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.dp.blackhole.common.MessagePB.Message.MessageType value = com.dp.blackhole.common.MessagePB.Message.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.dp.blackhole.common.AppRegPB.AppReg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = appReg_.toBuilder();
              }
              appReg_ = input.readMessage(com.dp.blackhole.common.AppRegPB.AppReg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(appReg_);
                appReg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.dp.blackhole.common.AssignCollectorPB.AssignCollector.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = assignCollector_.toBuilder();
              }
              assignCollector_ = input.readMessage(com.dp.blackhole.common.AssignCollectorPB.AssignCollector.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(assignCollector_);
                assignCollector_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.dp.blackhole.common.AppRollPB.AppRoll.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = appRoll_.toBuilder();
              }
              appRoll_ = input.readMessage(com.dp.blackhole.common.AppRollPB.AppRoll.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(appRoll_);
                appRoll_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dp.blackhole.common.MessagePB.internal_static_blackhole_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dp.blackhole.common.MessagePB.internal_static_blackhole_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dp.blackhole.common.MessagePB.Message.class, com.dp.blackhole.common.MessagePB.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code blackhole.Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HEARTBEAT = 0;</code>
       */
      HEARTBEAT(0, 0),
      /**
       * <code>APP_REG = 1;</code>
       */
      APP_REG(1, 1),
      /**
       * <code>HANDLER_REG = 2;</code>
       */
      HANDLER_REG(2, 2),
      /**
       * <code>REPLY_HANDLER = 3;</code>
       */
      REPLY_HANDLER(3, 3),
      /**
       * <code>ASSIGN_HANDLER = 4;</code>
       */
      ASSIGN_HANDLER(4, 4),
      /**
       * <code>APP_RECOVERY = 5;</code>
       */
      APP_RECOVERY(5, 5),
      /**
       * <code>HDFS_UPLOAD = 6;</code>
       */
      HDFS_UPLOAD(6, 6),
      /**
       * <code>HDFS_RECOVERY = 7;</code>
       */
      HDFS_RECOVERY(7, 7),
      /**
       * <code>APP_ROLL = 8;</code>
       */
      APP_ROLL(8, 8),
      ;

      /**
       * <code>HEARTBEAT = 0;</code>
       */
      public static final int HEARTBEAT_VALUE = 0;
      /**
       * <code>APP_REG = 1;</code>
       */
      public static final int APP_REG_VALUE = 1;
      /**
       * <code>HANDLER_REG = 2;</code>
       */
      public static final int HANDLER_REG_VALUE = 2;
      /**
       * <code>REPLY_HANDLER = 3;</code>
       */
      public static final int REPLY_HANDLER_VALUE = 3;
      /**
       * <code>ASSIGN_HANDLER = 4;</code>
       */
      public static final int ASSIGN_HANDLER_VALUE = 4;
      /**
       * <code>APP_RECOVERY = 5;</code>
       */
      public static final int APP_RECOVERY_VALUE = 5;
      /**
       * <code>HDFS_UPLOAD = 6;</code>
       */
      public static final int HDFS_UPLOAD_VALUE = 6;
      /**
       * <code>HDFS_RECOVERY = 7;</code>
       */
      public static final int HDFS_RECOVERY_VALUE = 7;
      /**
       * <code>APP_ROLL = 8;</code>
       */
      public static final int APP_ROLL_VALUE = 8;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return HEARTBEAT;
          case 1: return APP_REG;
          case 2: return HANDLER_REG;
          case 3: return REPLY_HANDLER;
          case 4: return ASSIGN_HANDLER;
          case 5: return APP_RECOVERY;
          case 6: return HDFS_UPLOAD;
          case 7: return HDFS_RECOVERY;
          case 8: return APP_ROLL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.dp.blackhole.common.MessagePB.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:blackhole.Message.MessageType)
    }

    private int bitField0_;
    // required .blackhole.Message.MessageType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.dp.blackhole.common.MessagePB.Message.MessageType type_;
    /**
     * <code>required .blackhole.Message.MessageType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .blackhole.Message.MessageType type = 1;</code>
     */
    public com.dp.blackhole.common.MessagePB.Message.MessageType getType() {
      return type_;
    }

    // optional .blackhole.AppReg appReg = 2;
    public static final int APPREG_FIELD_NUMBER = 2;
    private com.dp.blackhole.common.AppRegPB.AppReg appReg_;
    /**
     * <code>optional .blackhole.AppReg appReg = 2;</code>
     */
    public boolean hasAppReg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .blackhole.AppReg appReg = 2;</code>
     */
    public com.dp.blackhole.common.AppRegPB.AppReg getAppReg() {
      return appReg_;
    }
    /**
     * <code>optional .blackhole.AppReg appReg = 2;</code>
     */
    public com.dp.blackhole.common.AppRegPB.AppRegOrBuilder getAppRegOrBuilder() {
      return appReg_;
    }

    // optional .blackhole.AssignCollector assignCollector = 3;
    public static final int ASSIGNCOLLECTOR_FIELD_NUMBER = 3;
    private com.dp.blackhole.common.AssignCollectorPB.AssignCollector assignCollector_;
    /**
     * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
     */
    public boolean hasAssignCollector() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
     */
    public com.dp.blackhole.common.AssignCollectorPB.AssignCollector getAssignCollector() {
      return assignCollector_;
    }
    /**
     * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
     */
    public com.dp.blackhole.common.AssignCollectorPB.AssignCollectorOrBuilder getAssignCollectorOrBuilder() {
      return assignCollector_;
    }

    // optional .blackhole.AppRoll appRoll = 4;
    public static final int APPROLL_FIELD_NUMBER = 4;
    private com.dp.blackhole.common.AppRollPB.AppRoll appRoll_;
    /**
     * <code>optional .blackhole.AppRoll appRoll = 4;</code>
     */
    public boolean hasAppRoll() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .blackhole.AppRoll appRoll = 4;</code>
     */
    public com.dp.blackhole.common.AppRollPB.AppRoll getAppRoll() {
      return appRoll_;
    }
    /**
     * <code>optional .blackhole.AppRoll appRoll = 4;</code>
     */
    public com.dp.blackhole.common.AppRollPB.AppRollOrBuilder getAppRollOrBuilder() {
      return appRoll_;
    }

    private void initFields() {
      type_ = com.dp.blackhole.common.MessagePB.Message.MessageType.HEARTBEAT;
      appReg_ = com.dp.blackhole.common.AppRegPB.AppReg.getDefaultInstance();
      assignCollector_ = com.dp.blackhole.common.AssignCollectorPB.AssignCollector.getDefaultInstance();
      appRoll_ = com.dp.blackhole.common.AppRollPB.AppRoll.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAppReg()) {
        if (!getAppReg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasAssignCollector()) {
        if (!getAssignCollector().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasAppRoll()) {
        if (!getAppRoll().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, appReg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, assignCollector_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, appRoll_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, appReg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, assignCollector_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, appRoll_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dp.blackhole.common.MessagePB.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dp.blackhole.common.MessagePB.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dp.blackhole.common.MessagePB.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dp.blackhole.common.MessagePB.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dp.blackhole.common.MessagePB.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dp.blackhole.common.MessagePB.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dp.blackhole.common.MessagePB.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dp.blackhole.common.MessagePB.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dp.blackhole.common.MessagePB.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dp.blackhole.common.MessagePB.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dp.blackhole.common.MessagePB.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code blackhole.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dp.blackhole.common.MessagePB.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dp.blackhole.common.MessagePB.internal_static_blackhole_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dp.blackhole.common.MessagePB.internal_static_blackhole_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dp.blackhole.common.MessagePB.Message.class, com.dp.blackhole.common.MessagePB.Message.Builder.class);
      }

      // Construct using com.dp.blackhole.common.MessagePB.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAppRegFieldBuilder();
          getAssignCollectorFieldBuilder();
          getAppRollFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.dp.blackhole.common.MessagePB.Message.MessageType.HEARTBEAT;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (appRegBuilder_ == null) {
          appReg_ = com.dp.blackhole.common.AppRegPB.AppReg.getDefaultInstance();
        } else {
          appRegBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (assignCollectorBuilder_ == null) {
          assignCollector_ = com.dp.blackhole.common.AssignCollectorPB.AssignCollector.getDefaultInstance();
        } else {
          assignCollectorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (appRollBuilder_ == null) {
          appRoll_ = com.dp.blackhole.common.AppRollPB.AppRoll.getDefaultInstance();
        } else {
          appRollBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dp.blackhole.common.MessagePB.internal_static_blackhole_Message_descriptor;
      }

      public com.dp.blackhole.common.MessagePB.Message getDefaultInstanceForType() {
        return com.dp.blackhole.common.MessagePB.Message.getDefaultInstance();
      }

      public com.dp.blackhole.common.MessagePB.Message build() {
        com.dp.blackhole.common.MessagePB.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dp.blackhole.common.MessagePB.Message buildPartial() {
        com.dp.blackhole.common.MessagePB.Message result = new com.dp.blackhole.common.MessagePB.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (appRegBuilder_ == null) {
          result.appReg_ = appReg_;
        } else {
          result.appReg_ = appRegBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (assignCollectorBuilder_ == null) {
          result.assignCollector_ = assignCollector_;
        } else {
          result.assignCollector_ = assignCollectorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (appRollBuilder_ == null) {
          result.appRoll_ = appRoll_;
        } else {
          result.appRoll_ = appRollBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dp.blackhole.common.MessagePB.Message) {
          return mergeFrom((com.dp.blackhole.common.MessagePB.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dp.blackhole.common.MessagePB.Message other) {
        if (other == com.dp.blackhole.common.MessagePB.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAppReg()) {
          mergeAppReg(other.getAppReg());
        }
        if (other.hasAssignCollector()) {
          mergeAssignCollector(other.getAssignCollector());
        }
        if (other.hasAppRoll()) {
          mergeAppRoll(other.getAppRoll());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasAppReg()) {
          if (!getAppReg().isInitialized()) {
            
            return false;
          }
        }
        if (hasAssignCollector()) {
          if (!getAssignCollector().isInitialized()) {
            
            return false;
          }
        }
        if (hasAppRoll()) {
          if (!getAppRoll().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dp.blackhole.common.MessagePB.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dp.blackhole.common.MessagePB.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .blackhole.Message.MessageType type = 1;
      private com.dp.blackhole.common.MessagePB.Message.MessageType type_ = com.dp.blackhole.common.MessagePB.Message.MessageType.HEARTBEAT;
      /**
       * <code>required .blackhole.Message.MessageType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .blackhole.Message.MessageType type = 1;</code>
       */
      public com.dp.blackhole.common.MessagePB.Message.MessageType getType() {
        return type_;
      }
      /**
       * <code>required .blackhole.Message.MessageType type = 1;</code>
       */
      public Builder setType(com.dp.blackhole.common.MessagePB.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .blackhole.Message.MessageType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.dp.blackhole.common.MessagePB.Message.MessageType.HEARTBEAT;
        onChanged();
        return this;
      }

      // optional .blackhole.AppReg appReg = 2;
      private com.dp.blackhole.common.AppRegPB.AppReg appReg_ = com.dp.blackhole.common.AppRegPB.AppReg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.dp.blackhole.common.AppRegPB.AppReg, com.dp.blackhole.common.AppRegPB.AppReg.Builder, com.dp.blackhole.common.AppRegPB.AppRegOrBuilder> appRegBuilder_;
      /**
       * <code>optional .blackhole.AppReg appReg = 2;</code>
       */
      public boolean hasAppReg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .blackhole.AppReg appReg = 2;</code>
       */
      public com.dp.blackhole.common.AppRegPB.AppReg getAppReg() {
        if (appRegBuilder_ == null) {
          return appReg_;
        } else {
          return appRegBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .blackhole.AppReg appReg = 2;</code>
       */
      public Builder setAppReg(com.dp.blackhole.common.AppRegPB.AppReg value) {
        if (appRegBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          appReg_ = value;
          onChanged();
        } else {
          appRegBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .blackhole.AppReg appReg = 2;</code>
       */
      public Builder setAppReg(
          com.dp.blackhole.common.AppRegPB.AppReg.Builder builderForValue) {
        if (appRegBuilder_ == null) {
          appReg_ = builderForValue.build();
          onChanged();
        } else {
          appRegBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .blackhole.AppReg appReg = 2;</code>
       */
      public Builder mergeAppReg(com.dp.blackhole.common.AppRegPB.AppReg value) {
        if (appRegBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              appReg_ != com.dp.blackhole.common.AppRegPB.AppReg.getDefaultInstance()) {
            appReg_ =
              com.dp.blackhole.common.AppRegPB.AppReg.newBuilder(appReg_).mergeFrom(value).buildPartial();
          } else {
            appReg_ = value;
          }
          onChanged();
        } else {
          appRegBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .blackhole.AppReg appReg = 2;</code>
       */
      public Builder clearAppReg() {
        if (appRegBuilder_ == null) {
          appReg_ = com.dp.blackhole.common.AppRegPB.AppReg.getDefaultInstance();
          onChanged();
        } else {
          appRegBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .blackhole.AppReg appReg = 2;</code>
       */
      public com.dp.blackhole.common.AppRegPB.AppReg.Builder getAppRegBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getAppRegFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .blackhole.AppReg appReg = 2;</code>
       */
      public com.dp.blackhole.common.AppRegPB.AppRegOrBuilder getAppRegOrBuilder() {
        if (appRegBuilder_ != null) {
          return appRegBuilder_.getMessageOrBuilder();
        } else {
          return appReg_;
        }
      }
      /**
       * <code>optional .blackhole.AppReg appReg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.dp.blackhole.common.AppRegPB.AppReg, com.dp.blackhole.common.AppRegPB.AppReg.Builder, com.dp.blackhole.common.AppRegPB.AppRegOrBuilder> 
          getAppRegFieldBuilder() {
        if (appRegBuilder_ == null) {
          appRegBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.dp.blackhole.common.AppRegPB.AppReg, com.dp.blackhole.common.AppRegPB.AppReg.Builder, com.dp.blackhole.common.AppRegPB.AppRegOrBuilder>(
                  appReg_,
                  getParentForChildren(),
                  isClean());
          appReg_ = null;
        }
        return appRegBuilder_;
      }

      // optional .blackhole.AssignCollector assignCollector = 3;
      private com.dp.blackhole.common.AssignCollectorPB.AssignCollector assignCollector_ = com.dp.blackhole.common.AssignCollectorPB.AssignCollector.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.dp.blackhole.common.AssignCollectorPB.AssignCollector, com.dp.blackhole.common.AssignCollectorPB.AssignCollector.Builder, com.dp.blackhole.common.AssignCollectorPB.AssignCollectorOrBuilder> assignCollectorBuilder_;
      /**
       * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
       */
      public boolean hasAssignCollector() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
       */
      public com.dp.blackhole.common.AssignCollectorPB.AssignCollector getAssignCollector() {
        if (assignCollectorBuilder_ == null) {
          return assignCollector_;
        } else {
          return assignCollectorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
       */
      public Builder setAssignCollector(com.dp.blackhole.common.AssignCollectorPB.AssignCollector value) {
        if (assignCollectorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          assignCollector_ = value;
          onChanged();
        } else {
          assignCollectorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
       */
      public Builder setAssignCollector(
          com.dp.blackhole.common.AssignCollectorPB.AssignCollector.Builder builderForValue) {
        if (assignCollectorBuilder_ == null) {
          assignCollector_ = builderForValue.build();
          onChanged();
        } else {
          assignCollectorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
       */
      public Builder mergeAssignCollector(com.dp.blackhole.common.AssignCollectorPB.AssignCollector value) {
        if (assignCollectorBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              assignCollector_ != com.dp.blackhole.common.AssignCollectorPB.AssignCollector.getDefaultInstance()) {
            assignCollector_ =
              com.dp.blackhole.common.AssignCollectorPB.AssignCollector.newBuilder(assignCollector_).mergeFrom(value).buildPartial();
          } else {
            assignCollector_ = value;
          }
          onChanged();
        } else {
          assignCollectorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
       */
      public Builder clearAssignCollector() {
        if (assignCollectorBuilder_ == null) {
          assignCollector_ = com.dp.blackhole.common.AssignCollectorPB.AssignCollector.getDefaultInstance();
          onChanged();
        } else {
          assignCollectorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
       */
      public com.dp.blackhole.common.AssignCollectorPB.AssignCollector.Builder getAssignCollectorBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAssignCollectorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
       */
      public com.dp.blackhole.common.AssignCollectorPB.AssignCollectorOrBuilder getAssignCollectorOrBuilder() {
        if (assignCollectorBuilder_ != null) {
          return assignCollectorBuilder_.getMessageOrBuilder();
        } else {
          return assignCollector_;
        }
      }
      /**
       * <code>optional .blackhole.AssignCollector assignCollector = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.dp.blackhole.common.AssignCollectorPB.AssignCollector, com.dp.blackhole.common.AssignCollectorPB.AssignCollector.Builder, com.dp.blackhole.common.AssignCollectorPB.AssignCollectorOrBuilder> 
          getAssignCollectorFieldBuilder() {
        if (assignCollectorBuilder_ == null) {
          assignCollectorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.dp.blackhole.common.AssignCollectorPB.AssignCollector, com.dp.blackhole.common.AssignCollectorPB.AssignCollector.Builder, com.dp.blackhole.common.AssignCollectorPB.AssignCollectorOrBuilder>(
                  assignCollector_,
                  getParentForChildren(),
                  isClean());
          assignCollector_ = null;
        }
        return assignCollectorBuilder_;
      }

      // optional .blackhole.AppRoll appRoll = 4;
      private com.dp.blackhole.common.AppRollPB.AppRoll appRoll_ = com.dp.blackhole.common.AppRollPB.AppRoll.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.dp.blackhole.common.AppRollPB.AppRoll, com.dp.blackhole.common.AppRollPB.AppRoll.Builder, com.dp.blackhole.common.AppRollPB.AppRollOrBuilder> appRollBuilder_;
      /**
       * <code>optional .blackhole.AppRoll appRoll = 4;</code>
       */
      public boolean hasAppRoll() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .blackhole.AppRoll appRoll = 4;</code>
       */
      public com.dp.blackhole.common.AppRollPB.AppRoll getAppRoll() {
        if (appRollBuilder_ == null) {
          return appRoll_;
        } else {
          return appRollBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .blackhole.AppRoll appRoll = 4;</code>
       */
      public Builder setAppRoll(com.dp.blackhole.common.AppRollPB.AppRoll value) {
        if (appRollBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          appRoll_ = value;
          onChanged();
        } else {
          appRollBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .blackhole.AppRoll appRoll = 4;</code>
       */
      public Builder setAppRoll(
          com.dp.blackhole.common.AppRollPB.AppRoll.Builder builderForValue) {
        if (appRollBuilder_ == null) {
          appRoll_ = builderForValue.build();
          onChanged();
        } else {
          appRollBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .blackhole.AppRoll appRoll = 4;</code>
       */
      public Builder mergeAppRoll(com.dp.blackhole.common.AppRollPB.AppRoll value) {
        if (appRollBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              appRoll_ != com.dp.blackhole.common.AppRollPB.AppRoll.getDefaultInstance()) {
            appRoll_ =
              com.dp.blackhole.common.AppRollPB.AppRoll.newBuilder(appRoll_).mergeFrom(value).buildPartial();
          } else {
            appRoll_ = value;
          }
          onChanged();
        } else {
          appRollBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .blackhole.AppRoll appRoll = 4;</code>
       */
      public Builder clearAppRoll() {
        if (appRollBuilder_ == null) {
          appRoll_ = com.dp.blackhole.common.AppRollPB.AppRoll.getDefaultInstance();
          onChanged();
        } else {
          appRollBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .blackhole.AppRoll appRoll = 4;</code>
       */
      public com.dp.blackhole.common.AppRollPB.AppRoll.Builder getAppRollBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getAppRollFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .blackhole.AppRoll appRoll = 4;</code>
       */
      public com.dp.blackhole.common.AppRollPB.AppRollOrBuilder getAppRollOrBuilder() {
        if (appRollBuilder_ != null) {
          return appRollBuilder_.getMessageOrBuilder();
        } else {
          return appRoll_;
        }
      }
      /**
       * <code>optional .blackhole.AppRoll appRoll = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.dp.blackhole.common.AppRollPB.AppRoll, com.dp.blackhole.common.AppRollPB.AppRoll.Builder, com.dp.blackhole.common.AppRollPB.AppRollOrBuilder> 
          getAppRollFieldBuilder() {
        if (appRollBuilder_ == null) {
          appRollBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.dp.blackhole.common.AppRollPB.AppRoll, com.dp.blackhole.common.AppRollPB.AppRoll.Builder, com.dp.blackhole.common.AppRollPB.AppRollOrBuilder>(
                  appRoll_,
                  getParentForChildren(),
                  isClean());
          appRoll_ = null;
        }
        return appRollBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:blackhole.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:blackhole.Message)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_blackhole_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_blackhole_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\tblackhole\032\014AppReg.proto" +
      "\032\025AssignCollector.proto\032\rAppRoll.proto\"\334" +
      "\002\n\007Message\022,\n\004type\030\001 \002(\0162\036.blackhole.Mes" +
      "sage.MessageType\022!\n\006appReg\030\002 \001(\0132\021.black" +
      "hole.AppReg\0223\n\017assignCollector\030\003 \001(\0132\032.b" +
      "lackhole.AssignCollector\022#\n\007appRoll\030\004 \001(" +
      "\0132\022.blackhole.AppRoll\"\245\001\n\013MessageType\022\r\n" +
      "\tHEARTBEAT\020\000\022\013\n\007APP_REG\020\001\022\017\n\013HANDLER_REG" +
      "\020\002\022\021\n\rREPLY_HANDLER\020\003\022\022\n\016ASSIGN_HANDLER\020" +
      "\004\022\020\n\014APP_RECOVERY\020\005\022\017\n\013HDFS_UPLOAD\020\006\022\021\n\r",
      "HDFS_RECOVERY\020\007\022\014\n\010APP_ROLL\020\010B$\n\027com.dp." +
      "blackhole.commonB\tMessagePB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_blackhole_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_blackhole_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_blackhole_Message_descriptor,
              new java.lang.String[] { "Type", "AppReg", "AssignCollector", "AppRoll", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dp.blackhole.common.AppRegPB.getDescriptor(),
          com.dp.blackhole.common.AssignCollectorPB.getDescriptor(),
          com.dp.blackhole.common.AppRollPB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
