// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignCollector.proto

package com.dp.blackhole.protocol.control;

public final class AssignCollectorPB {
  private AssignCollectorPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class AssignCollector extends
      com.google.protobuf.GeneratedMessage {
    // Use AssignCollector.newBuilder() to construct.
    private AssignCollector() {
      initFields();
    }
    private AssignCollector(boolean noInit) {}
    
    private static final AssignCollector defaultInstance;
    public static AssignCollector getDefaultInstance() {
      return defaultInstance;
    }
    
    public AssignCollector getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dp.blackhole.protocol.control.AssignCollectorPB.internal_static_blackhole_AssignCollector_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dp.blackhole.protocol.control.AssignCollectorPB.internal_static_blackhole_AssignCollector_fieldAccessorTable;
    }
    
    // required string app_name = 1;
    public static final int APP_NAME_FIELD_NUMBER = 1;
    private boolean hasAppName;
    private java.lang.String appName_ = "";
    public boolean hasAppName() { return hasAppName; }
    public java.lang.String getAppName() { return appName_; }
    
    // required string collector_server = 2;
    public static final int COLLECTOR_SERVER_FIELD_NUMBER = 2;
    private boolean hasCollectorServer;
    private java.lang.String collectorServer_ = "";
    public boolean hasCollectorServer() { return hasCollectorServer; }
    public java.lang.String getCollectorServer() { return collectorServer_; }
    
    // required int32 broker_port = 3;
    public static final int BROKER_PORT_FIELD_NUMBER = 3;
    private boolean hasBrokerPort;
    private int brokerPort_ = 0;
    public boolean hasBrokerPort() { return hasBrokerPort; }
    public int getBrokerPort() { return brokerPort_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasAppName) return false;
      if (!hasCollectorServer) return false;
      if (!hasBrokerPort) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAppName()) {
        output.writeString(1, getAppName());
      }
      if (hasCollectorServer()) {
        output.writeString(2, getCollectorServer());
      }
      if (hasBrokerPort()) {
        output.writeInt32(3, getBrokerPort());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAppName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAppName());
      }
      if (hasCollectorServer()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getCollectorServer());
      }
      if (hasBrokerPort()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getBrokerPort());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector result;
      
      // Construct using com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector();
        return builder;
      }
      
      protected com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector.getDescriptor();
      }
      
      public com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector getDefaultInstanceForType() {
        return com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector) {
          return mergeFrom((com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector other) {
        if (other == com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector.getDefaultInstance()) return this;
        if (other.hasAppName()) {
          setAppName(other.getAppName());
        }
        if (other.hasCollectorServer()) {
          setCollectorServer(other.getCollectorServer());
        }
        if (other.hasBrokerPort()) {
          setBrokerPort(other.getBrokerPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAppName(input.readString());
              break;
            }
            case 18: {
              setCollectorServer(input.readString());
              break;
            }
            case 24: {
              setBrokerPort(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string app_name = 1;
      public boolean hasAppName() {
        return result.hasAppName();
      }
      public java.lang.String getAppName() {
        return result.getAppName();
      }
      public Builder setAppName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAppName = true;
        result.appName_ = value;
        return this;
      }
      public Builder clearAppName() {
        result.hasAppName = false;
        result.appName_ = getDefaultInstance().getAppName();
        return this;
      }
      
      // required string collector_server = 2;
      public boolean hasCollectorServer() {
        return result.hasCollectorServer();
      }
      public java.lang.String getCollectorServer() {
        return result.getCollectorServer();
      }
      public Builder setCollectorServer(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCollectorServer = true;
        result.collectorServer_ = value;
        return this;
      }
      public Builder clearCollectorServer() {
        result.hasCollectorServer = false;
        result.collectorServer_ = getDefaultInstance().getCollectorServer();
        return this;
      }
      
      // required int32 broker_port = 3;
      public boolean hasBrokerPort() {
        return result.hasBrokerPort();
      }
      public int getBrokerPort() {
        return result.getBrokerPort();
      }
      public Builder setBrokerPort(int value) {
        result.hasBrokerPort = true;
        result.brokerPort_ = value;
        return this;
      }
      public Builder clearBrokerPort() {
        result.hasBrokerPort = false;
        result.brokerPort_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:blackhole.AssignCollector)
    }
    
    static {
      defaultInstance = new AssignCollector(true);
      com.dp.blackhole.protocol.control.AssignCollectorPB.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:blackhole.AssignCollector)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_blackhole_AssignCollector_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_blackhole_AssignCollector_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025AssignCollector.proto\022\tblackhole\"R\n\017As" +
      "signCollector\022\020\n\010app_name\030\001 \002(\t\022\030\n\020colle" +
      "ctor_server\030\002 \002(\t\022\023\n\013broker_port\030\003 \002(\005B6" +
      "\n!com.dp.blackhole.protocol.controlB\021Ass" +
      "ignCollectorPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_blackhole_AssignCollector_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_blackhole_AssignCollector_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_blackhole_AssignCollector_descriptor,
              new java.lang.String[] { "AppName", "CollectorServer", "BrokerPort", },
              com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector.class,
              com.dp.blackhole.protocol.control.AssignCollectorPB.AssignCollector.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
