// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FollowerSyncStatus.proto

package com.dp.blackhole.protocol.control;

public final class FollowerSyncStatusPB {
  private FollowerSyncStatusPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FollowerSyncStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 entropy = 1;
    /**
     * <code>required int32 entropy = 1;</code>
     */
    boolean hasEntropy();
    /**
     * <code>required int32 entropy = 1;</code>
     */
    int getEntropy();

    // required string topic = 2;
    /**
     * <code>required string topic = 2;</code>
     */
    boolean hasTopic();
    /**
     * <code>required string topic = 2;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>required string topic = 2;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    // required string partitionId = 3;
    /**
     * <code>required string partitionId = 3;</code>
     */
    boolean hasPartitionId();
    /**
     * <code>required string partitionId = 3;</code>
     */
    java.lang.String getPartitionId();
    /**
     * <code>required string partitionId = 3;</code>
     */
    com.google.protobuf.ByteString
        getPartitionIdBytes();

    // required string follower = 4;
    /**
     * <code>required string follower = 4;</code>
     */
    boolean hasFollower();
    /**
     * <code>required string follower = 4;</code>
     */
    java.lang.String getFollower();
    /**
     * <code>required string follower = 4;</code>
     */
    com.google.protobuf.ByteString
        getFollowerBytes();

    // required bool syncStatus = 5;
    /**
     * <code>required bool syncStatus = 5;</code>
     */
    boolean hasSyncStatus();
    /**
     * <code>required bool syncStatus = 5;</code>
     */
    boolean getSyncStatus();
  }
  /**
   * Protobuf type {@code blackhole.FollowerSyncStatus}
   */
  public static final class FollowerSyncStatus extends
      com.google.protobuf.GeneratedMessage
      implements FollowerSyncStatusOrBuilder {
    // Use FollowerSyncStatus.newBuilder() to construct.
    private FollowerSyncStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FollowerSyncStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FollowerSyncStatus defaultInstance;
    public static FollowerSyncStatus getDefaultInstance() {
      return defaultInstance;
    }

    public FollowerSyncStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FollowerSyncStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              entropy_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              topic_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              partitionId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              follower_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              syncStatus_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dp.blackhole.protocol.control.FollowerSyncStatusPB.internal_static_blackhole_FollowerSyncStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dp.blackhole.protocol.control.FollowerSyncStatusPB.internal_static_blackhole_FollowerSyncStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus.class, com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<FollowerSyncStatus> PARSER =
        new com.google.protobuf.AbstractParser<FollowerSyncStatus>() {
      public FollowerSyncStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FollowerSyncStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FollowerSyncStatus> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 entropy = 1;
    public static final int ENTROPY_FIELD_NUMBER = 1;
    private int entropy_;
    /**
     * <code>required int32 entropy = 1;</code>
     */
    public boolean hasEntropy() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 entropy = 1;</code>
     */
    public int getEntropy() {
      return entropy_;
    }

    // required string topic = 2;
    public static final int TOPIC_FIELD_NUMBER = 2;
    private java.lang.Object topic_;
    /**
     * <code>required string topic = 2;</code>
     */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string topic = 2;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string topic = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string partitionId = 3;
    public static final int PARTITIONID_FIELD_NUMBER = 3;
    private java.lang.Object partitionId_;
    /**
     * <code>required string partitionId = 3;</code>
     */
    public boolean hasPartitionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string partitionId = 3;</code>
     */
    public java.lang.String getPartitionId() {
      java.lang.Object ref = partitionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          partitionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string partitionId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPartitionIdBytes() {
      java.lang.Object ref = partitionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partitionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string follower = 4;
    public static final int FOLLOWER_FIELD_NUMBER = 4;
    private java.lang.Object follower_;
    /**
     * <code>required string follower = 4;</code>
     */
    public boolean hasFollower() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string follower = 4;</code>
     */
    public java.lang.String getFollower() {
      java.lang.Object ref = follower_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          follower_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string follower = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFollowerBytes() {
      java.lang.Object ref = follower_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        follower_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bool syncStatus = 5;
    public static final int SYNCSTATUS_FIELD_NUMBER = 5;
    private boolean syncStatus_;
    /**
     * <code>required bool syncStatus = 5;</code>
     */
    public boolean hasSyncStatus() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool syncStatus = 5;</code>
     */
    public boolean getSyncStatus() {
      return syncStatus_;
    }

    private void initFields() {
      entropy_ = 0;
      topic_ = "";
      partitionId_ = "";
      follower_ = "";
      syncStatus_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEntropy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTopic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPartitionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFollower()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSyncStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, entropy_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTopicBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPartitionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFollowerBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, syncStatus_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, entropy_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTopicBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPartitionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFollowerBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, syncStatus_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code blackhole.FollowerSyncStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dp.blackhole.protocol.control.FollowerSyncStatusPB.internal_static_blackhole_FollowerSyncStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dp.blackhole.protocol.control.FollowerSyncStatusPB.internal_static_blackhole_FollowerSyncStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus.class, com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus.Builder.class);
      }

      // Construct using com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        entropy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        partitionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        follower_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        syncStatus_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dp.blackhole.protocol.control.FollowerSyncStatusPB.internal_static_blackhole_FollowerSyncStatus_descriptor;
      }

      public com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus getDefaultInstanceForType() {
        return com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus.getDefaultInstance();
      }

      public com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus build() {
        com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus buildPartial() {
        com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus result = new com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.entropy_ = entropy_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.topic_ = topic_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.partitionId_ = partitionId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.follower_ = follower_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.syncStatus_ = syncStatus_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus) {
          return mergeFrom((com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus other) {
        if (other == com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus.getDefaultInstance()) return this;
        if (other.hasEntropy()) {
          setEntropy(other.getEntropy());
        }
        if (other.hasTopic()) {
          bitField0_ |= 0x00000002;
          topic_ = other.topic_;
          onChanged();
        }
        if (other.hasPartitionId()) {
          bitField0_ |= 0x00000004;
          partitionId_ = other.partitionId_;
          onChanged();
        }
        if (other.hasFollower()) {
          bitField0_ |= 0x00000008;
          follower_ = other.follower_;
          onChanged();
        }
        if (other.hasSyncStatus()) {
          setSyncStatus(other.getSyncStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEntropy()) {
          
          return false;
        }
        if (!hasTopic()) {
          
          return false;
        }
        if (!hasPartitionId()) {
          
          return false;
        }
        if (!hasFollower()) {
          
          return false;
        }
        if (!hasSyncStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dp.blackhole.protocol.control.FollowerSyncStatusPB.FollowerSyncStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 entropy = 1;
      private int entropy_ ;
      /**
       * <code>required int32 entropy = 1;</code>
       */
      public boolean hasEntropy() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 entropy = 1;</code>
       */
      public int getEntropy() {
        return entropy_;
      }
      /**
       * <code>required int32 entropy = 1;</code>
       */
      public Builder setEntropy(int value) {
        bitField0_ |= 0x00000001;
        entropy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 entropy = 1;</code>
       */
      public Builder clearEntropy() {
        bitField0_ = (bitField0_ & ~0x00000001);
        entropy_ = 0;
        onChanged();
        return this;
      }

      // required string topic = 2;
      private java.lang.Object topic_ = "";
      /**
       * <code>required string topic = 2;</code>
       */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string topic = 2;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string topic = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string topic = 2;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 2;</code>
       */
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000002);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 2;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        topic_ = value;
        onChanged();
        return this;
      }

      // required string partitionId = 3;
      private java.lang.Object partitionId_ = "";
      /**
       * <code>required string partitionId = 3;</code>
       */
      public boolean hasPartitionId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string partitionId = 3;</code>
       */
      public java.lang.String getPartitionId() {
        java.lang.Object ref = partitionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          partitionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string partitionId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPartitionIdBytes() {
        java.lang.Object ref = partitionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partitionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string partitionId = 3;</code>
       */
      public Builder setPartitionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        partitionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string partitionId = 3;</code>
       */
      public Builder clearPartitionId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        partitionId_ = getDefaultInstance().getPartitionId();
        onChanged();
        return this;
      }
      /**
       * <code>required string partitionId = 3;</code>
       */
      public Builder setPartitionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        partitionId_ = value;
        onChanged();
        return this;
      }

      // required string follower = 4;
      private java.lang.Object follower_ = "";
      /**
       * <code>required string follower = 4;</code>
       */
      public boolean hasFollower() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string follower = 4;</code>
       */
      public java.lang.String getFollower() {
        java.lang.Object ref = follower_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          follower_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string follower = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFollowerBytes() {
        java.lang.Object ref = follower_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          follower_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string follower = 4;</code>
       */
      public Builder setFollower(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        follower_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string follower = 4;</code>
       */
      public Builder clearFollower() {
        bitField0_ = (bitField0_ & ~0x00000008);
        follower_ = getDefaultInstance().getFollower();
        onChanged();
        return this;
      }
      /**
       * <code>required string follower = 4;</code>
       */
      public Builder setFollowerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        follower_ = value;
        onChanged();
        return this;
      }

      // required bool syncStatus = 5;
      private boolean syncStatus_ ;
      /**
       * <code>required bool syncStatus = 5;</code>
       */
      public boolean hasSyncStatus() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool syncStatus = 5;</code>
       */
      public boolean getSyncStatus() {
        return syncStatus_;
      }
      /**
       * <code>required bool syncStatus = 5;</code>
       */
      public Builder setSyncStatus(boolean value) {
        bitField0_ |= 0x00000010;
        syncStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool syncStatus = 5;</code>
       */
      public Builder clearSyncStatus() {
        bitField0_ = (bitField0_ & ~0x00000010);
        syncStatus_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:blackhole.FollowerSyncStatus)
    }

    static {
      defaultInstance = new FollowerSyncStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:blackhole.FollowerSyncStatus)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_blackhole_FollowerSyncStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_blackhole_FollowerSyncStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030FollowerSyncStatus.proto\022\tblackhole\"o\n" +
      "\022FollowerSyncStatus\022\017\n\007entropy\030\001 \002(\005\022\r\n\005" +
      "topic\030\002 \002(\t\022\023\n\013partitionId\030\003 \002(\t\022\020\n\010foll" +
      "ower\030\004 \002(\t\022\022\n\nsyncStatus\030\005 \002(\010B9\n!com.dp" +
      ".blackhole.protocol.controlB\024FollowerSyn" +
      "cStatusPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_blackhole_FollowerSyncStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_blackhole_FollowerSyncStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_blackhole_FollowerSyncStatus_descriptor,
              new java.lang.String[] { "Entropy", "Topic", "PartitionId", "Follower", "SyncStatus", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
